# This file has been generated by node2nix 1.10.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "lnsocket-0.2.3" = {
      name = "lnsocket";
      packageName = "lnsocket";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lnsocket/-/lnsocket-0.2.3.tgz";
        sha512 = "CI4cMKefLkwb//WEyjyiHnVp5z60kfbhWiiGctGfDsXxJ8kRpXt7VgaTHFDAQ4cUaJ+paMXtAItLyVRu0OVdqw==";
      };
    };
    "minimist-1.2.6" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.6.tgz";
        sha512 = "Jsjnk4bw3YJqYzbdyBiNsPWHPfO++UGG749Cxs6peCu5Xg4nrena6OVxOYxrQTqww0Jmwt+Ref8rggumkTLz9Q==";
      };
    };
  };
  args = {
    name = "lnurl-commando";
    packageName = "lnurl-commando";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."lnsocket-0.2.3"
      sources."minimist-1.2.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "LNUrl Commando server";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
